-- Voeg 28 nieuwe avatars toe aan de winkel
INSERT INTO avatars (naam, prijs, afbeelding_url, is_actief) VALUES
('Balanseercapy', 30, '/avatars/capy_extra_1.png', true),
('Fitnesscapy', 30, '/avatars/capy_extra_2.png', true),
('Ondersteboven Capy', 30, '/avatars/capy_extra_3.png', true),
('Gekke Bekken Capy', 30, '/avatars/capy_extra_4.png', true),
('Feestcapy', 30, '/avatars/capy_extra_5.png', true),
('Knipoog Capy', 30, '/avatars/capy_extra_6.png', true),
('Coole Capy (Extra)', 30, '/avatars/capy_extra_7.png', true),
('Slaapcapy', 30, '/avatars/capy_extra_8.png', true),
('Luie Capy', 30, '/avatars/capy_extra_9.png', true),
('Verbaasde Capy', 30, '/avatars/capy_extra_10.png', true),
('Blije Capy', 30, '/avatars/capy_extra_11.png', true),
('Verdrietige Capy', 30, '/avatars/capy_extra_12.png', true),
('Boze Capy', 30, '/avatars/capy_extra_13.png', true),
('Geïrriteerde Capy', 30, '/avatars/capy_extra_14.png', true),
('Zweefcapy', 30, '/avatars/capy_extra_15.png', true),
('Zwemcapy', 30, '/avatars/capy_extra_16.png', true),
('Rennercapy', 30, '/avatars/capy_extra_17.png', true),
('Wortelcapy', 30, '/avatars/capy_extra_18.png', true),
('Leescapy', 30, '/avatars/capy_extra_19.png', true),
('Sterke Capy', 30, '/avatars/capy_extra_20.png', true),
('Gewichthefcapy', 30, '/avatars/capy_extra_21.png', true),
('Koning Capy', 30, '/avatars/capy_extra_22.png', true),
('Prins Capy', 30, '/avatars/capy_extra_23.png', true),
('Piraatcapy', 30, '/avatars/capy_extra_24.png', true),
('Astronautcapy', 30, '/avatars/capy_extra_25.png', true),
('Chefcapy', 30, '/avatars/capy_extra_26.png', true),
('Supercapy (Extra)', 30, '/avatars/capy_extra_27.png', true),
('Heldencapy', 30, '/avatars/capy_extra_28.png', true);
